import type { APIRoute } from 'astro';

// Import raw content of documentation files at build time
import agentContent from './doc-agent.md?raw';
import apiContent from './doc-api.md?raw';
import faqsContent from './doc-faqs.md?raw';
import firstStepsContent from './doc-first-steps.md?raw';
import newsData from '../../public/news.json';
import otherContent from './doc-other.md?raw';
import indexContent from './index.mdx?raw';
import priceContent from './price.md?raw';

interface DocFile {
  rawContent: string
  title: string
}

interface NewsItem {
  title: string
  description: string
}

interface NewsEntry {
  version: string
  date: string
  items: NewsItem[]
}

const SYSTEM_MESSAGE = `# b.tree agent docs

Compact machine context for b.tree integrated LLM agents. Source docs stay human-readable; this file is generated by deterministic cleanup/compression.

---

`;

const DOC_FILES: DocFile[] = [
  { rawContent: indexContent, title: 'Introduction' },
  { rawContent: priceContent, title: 'Costs & Price' },
  { rawContent: faqsContent, title: 'FAQs' },
  { rawContent: firstStepsContent, title: 'First Steps' },
  { rawContent: apiContent, title: 'API (Premium Feature)' },
  { rawContent: agentContent, title: 'AI Agent API' },
  { rawContent: otherContent, title: 'Other Features' },
];

const PHRASE_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\*\*/g, ''],
  [/\s+—\s+/g, ': '],
  [/\s+–\s+/g, ': '],
  [/\bThe b\.tree\b/g, 'b.tree'],
  [/\bthe b\.tree\b/g, 'b.tree'],
  [/\bbeekeeping web application\b/gi, 'beekeeping app'],
  [/\bbeekeeping web app\b/gi, 'beekeeping app'],
  [/\bProgressive Web Application \(PWA\)\b/g, 'PWA'],
  [/\bprogressive web application \(PWA\)\b/gi, 'PWA'],
  [/\bapplication\b/g, 'app'],
  [/\bApplication\b/g, 'App'],
  [/\bautomatically\b/g, 'auto'],
  [/\binformation\b/g, 'info'],
  [/\bapproximately\b/g, '~'],
  [/\bfor example\b/gi, 'e.g.'],
  [/\bthat allows you to\b/gi, 'to'],
  [/\bwhich allows you to\b/gi, 'to'],
  [/\byou can easily\b/gi, 'you can'],
  [/\beasily\b/gi, ''],
  [/\bsimply\b/gi, ''],
  [/\bjust\b/gi, ''],
  [/\bvery\b/gi, ''],
  [/\breally\b/gi, ''],
  [/\bfull read and write access\b/gi, 'read/write access'],
  [/\bthrough a secure, rate-limited, OpenAPI-documented endpoint\b/gi, 'via secure rate-limited OpenAPI endpoint'],
  [/\bIf you exceed the limit, you'll receive\b/gi, 'Over limit returns'],
  [/\bThe API key is only displayed once after creation\./g, 'API key shown once after creation.'],
  [/\bIt cannot be retrieved later\./g, 'Cannot retrieve later.'],
  [/\bNavigate to\b/g, 'Go to'],
  [/\bClick\b/g, 'Select'],
  [/\bInclude your key in\b/g, 'Put key in'],
  [/\bFetch the full\b/g, 'Fetch'],
  [/\bEach tool is available as\b/g, 'Each tool ='],
  [/\byou can\s+/gi, ''],
  [/\bit is possible to\s+/gi, ''],
  [/\bthere are\s+/gi, ''],
  [/\bthere is\s+/gi, ''],
  [/\bis available at\s+/gi, ': '],
  [/\bare available from\s+/gi, ': '],
  [/\b(?:a|an|the)\b\s*/gi, ''],
  [/\b(?:basically|actually)\b\s*/gi, ''],
  [/\b(?:sure|certainly|of course|happy to)\b[,!]?\s*/gi, ''],
  [/\b(?:maybe|probably|likely)\b\s*/gi, ''],
  [/\b(?:seems|appears) to be\b\s*/gi, ''],
];

const DROP_SENTENCE_PATTERNS = [
  /looking for/i,
  /look no further/i,
  /sign up/i,
  /so why not/i,
  /give it a try/i,
  /see the difference/i,
  /best way to use the app/i,
  /designed to cater/i,
  /that's why/i,
  /game-changer/i,
  /we hope to give you a fair system/i,
  /feel free to contact/i,
  /all kind of feedback/i,
  /my goal is/i,
  /i want to say thanks/i,
];

/**
 * Extract content from markdown/mdx, removing frontmatter, imports, images, and page-only HTML.
 * Keep links/code/URLs because agents need exact references.
 */
function extractContent(content: string): string {
  let cleanContent = content.replace(/^---[\s\S]*?---\n*/, '');

  cleanContent = cleanContent.replace(/^import\s[^\n]+\n/gm, '');
  cleanContent = cleanContent.replace(/<Image[^>]*\/>/g, '');
  cleanContent = cleanContent.replace(/<Image[^>]*>[\s\S]*?<\/Image>/g, '');
  cleanContent = cleanContent.replace(/<section[^>]*>[\s\S]*?<\/section>/g, '');
  cleanContent = cleanContent.replace(/<ul[^>]*>/g, '');
  cleanContent = cleanContent.replace(/<\/ul>/g, '');
  cleanContent = cleanContent.replace(/<li>([\s\S]*?)<\/li>/g, '- $1');
  cleanContent = cleanContent.replace(/<a\s+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g, '$2 ($1)');
  cleanContent = cleanContent.replace(/<!--[\s\S]*?-->/g, '');
  cleanContent = cleanContent.replace(/<hr\s*\/?>/g, '---');
  cleanContent = cleanContent.replace(/<[^>]+>/g, '');

  return cleanContent.trim();
}

function compactText(text: string): string {
  let compact = text.trim();

  for (const [pattern, replacement] of PHRASE_REPLACEMENTS) {
    compact = compact.replace(pattern, replacement);
  }

  compact = compact
    .replace(/\b(please|note that|in order to)\b/gi, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/\s+([,.:;!?])/g, '$1')
    .trim();

  return compact;
}

function compactProseBlock(block: string): string {
  const lines = block.split('\n');
  const isStructured = lines.some(line => /^\s*(?:#{1,6}\s+|[-*]\s+|\d+\.\s+|>\s*)/.test(line));

  if (isStructured) {
    return lines
      .map(line => compactText(line))
      .filter(Boolean)
      .join('\n');
  }

  return block
    .split(/(?<=[.!?])\s+/)
    .filter(sentence => !DROP_SENTENCE_PATTERNS.some(pattern => pattern.test(sentence)))
    .map(compactText)
    .filter(Boolean)
    .join(' ');
}

function compactContent(content: string): string {
  const extracted = extractContent(content);
  const blocks = extracted.split(/\n{2,}/);
  let inCodeFence = false;

  return blocks
    .map((block) => {
      if (!block.includes('```') && !inCodeFence) {
        return compactProseBlock(block);
      }

      return block
        .split('\n')
        .map((line) => {
          if (line.trim().startsWith('```')) {
            inCodeFence = !inCodeFence;
            return line.trimEnd();
          }

          return inCodeFence ? line.trimEnd() : compactText(line);
        })
        .join('\n')
        .trim();
    })
    .filter(Boolean)
    .join('\n\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function generateLatestNews(limit = 10): string {
  const entries = (newsData as Record<'en' | 'de', NewsEntry[]>).en.slice(0, limit);

  return entries
    .map((entry) => {
      const items = entry.items
        .map(item => `- ${compactText(item.title)}: ${compactText(item.description)}`)
        .join('\n');
      return `### ${entry.version} [${entry.date}]\n${items}`;
    })
    .join('\n\n');
}

/** Generates compact docs text for LLM/agent ingestion. */
function generateLlmsFullTxt(): string {
  let output = SYSTEM_MESSAGE;

  output += '## Latest Updates\n\n';
  output += generateLatestNews();
  output += '\n\n---\n\n';

  for (const doc of DOC_FILES) {
    output += `## ${doc.title}\n\n`;
    output += compactContent(doc.rawContent);
    output += '\n\n---\n\n';
  }

  return output.replace(/\n---\n\n$/, '\n');
}

export const GET: APIRoute = async () => {
  const content = generateLlmsFullTxt();
  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
};
